services:
  postgres:
    container_name: postgres
    image: postgres
    restart: unless-stopped
    volumes:
      - postgres:/var/lib/postgresql/data:rw
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 15s
      retries: 5
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: unless-stopped
    volumes:
      - pgadmin:/var/lib/pgadmin:rw
    ports:
      - "5050:80"
    healthcheck:
      test: [ "CMD", "wget", "-O", "-", "http://pgadmin/misc/ping" ]
      interval: 10s
      timeout: 15s
      retries: 5
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin

networks:
  default:
    name: projeto-extensao

volumes:
  pgadmin:
    external: false
  postgres:
    external: false